name: Learn You Node Actions

on:
  push:
    branches: [ "main" ]

jobs:
  js:
    name: js
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: install Dependencies
      run: npm install
   

